### ISSUE TITLE
Execution fails when no mathjax_csp config fields are set

### ISSUE THREAD

**Issue by MaximeKjaer** [fmeum/jekyll-mathjax-csp#1]
When no config options are set in `_config.yml`, the script throws an error:

```
$ jekyll build --trace

Configuration file: [redacted]
            Source: [redacted]
       Destination: [redacted]
 Incremental build: disabled. Enable with --incremental
      Generating...
    Rendering math: _posts/test.md
/var/lib/gems/2.3.0/gems/jekyll-mathjax-csp-1.0.0/lib/jekyll-mathjax-csp.rb:120:in `mathify': undefined method `[]' for nil:NilClass (NoMethodError)
```

<details>
<summary>Full stack trace</summary>
<pre><code>
/var/lib/gems/2.3.0/gems/jekyll-mathjax-csp-1.0.0/lib/jekyll-mathjax-csp.rb:120:in `mathify': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/jekyll-mathjax-csp-1.0.0/lib/jekyll-mathjax-csp.rb:188:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/hooks.rb:103:in `block in trigger'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/hooks.rb:102:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/hooks.rb:102:in `trigger'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/document.rb:352:in `trigger_hooks'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:480:in `render_regenerated'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `block in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `each_value'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:191:in `render'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:71:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
</code></pre>
</details>
<br/>  

As the stack trace says, this stems from [`jekyll-mathjax-csp.rb:120`](https://github.com/FabianHenneke/jekyll-mathjax-csp/blob/9266fcf2b9da507b973e389e8feeb71c34ad595a/lib/jekyll-mathjax-csp.rb#L120), where it is assumed that `config` exists, and the code fetches `config["strip_css"]`; but when no `mathjax_csp` field is present in `_config.yml`, this is equivalent to `nil["strip_css"]`, which throws an error.

Expected behavior (from my reading of the README), is that adding config fields to `_config.yml` is optional, and that by default the `config.mathjax_csp.strip_css` is considered false.

**Comment by fmeum** [comment]
Thanks for reporting this issue!

I made a small change in commit e864db091e59064523c51d06919b7ab6a56848d6 that should fix the problem. Please let me know whether it worked for you.

**Comment by MaximeKjaer** [comment]
That's perfect! Works beautifully 😃
