### ISSUE TITLE
Breaks with kramdown 2.2.0

### ISSUE THREAD

**Issue by MaximeKjaer** [fmeum/jekyll-mathjax-csp#6]
I recently tried to update kramdown from 2.1.0 to 2.2.0 on my site, but it broke the generation of math (i.e. it was no longer taking place).

From the [release notes](https://kramdown.gettalong.org/news.html) it seems that the generated HTML has changed slightly. Perhaps the solution is simply to tell kramdown not to prepare the output for any specific math engine, in which case the fix would be to add some documentation.

I don't really have time to look into it right now, but still wanted to write down this bug report. I will report back if I find a fix. In the meantime, I've stayed on kramdown 2.1.0.

**Comment by fmeum** [comment]
Thanks for the report. This may also be an issue with the dependency `mjpage`, but I will have to dive in deeper to figure out the root cause.

**Comment by fmeum** [comment]
It is https://github.com/gettalong/kramdown/commit/c3acf8df1db49d2456050f4456f3f542294e2e8f that broke the math generation: Whereas MathJax v2 consumed TeX in `<script type=math/tex>` tags, MathJax v3 expects TeX in `\(...\)` and `\[...\]`. This breaks the check for math in https://github.com/FabianHenneke/jekyll-mathjax-csp/blob/568a5daef2128dcee623044c621266711bb04de4/lib/jekyll-mathjax-csp.rb#L41 and the plugin will simply stop running. 

I have pushed version 1.3.0, which includes the fix https://github.com/FabianHenneke/jekyll-mathjax-csp/commit/12ff94f7393419322699a3d13fbc2dc992af962b. Could you check whether it resolves your problem?

**Comment by fmeum** [comment]
Please try with version 1.3.1, 1.3.0 did not fully fix the problem (see #7).

**Comment by MaximeKjaer** [comment]
I just tried with version 1.3.1, and it fixes the problem. Thank you for looking into this and fixing it!
