### ISSUE TITLE
Multiline Math Broken on Jekyll 4.0

### ISSUE THREAD

**Issue by c0nn3r** [fmeum/jekyll-mathjax-csp#7]
Steps to reproduce:

1. I created a new blank site. (`jekyll new jekyll-mathjax-csp-test --blank`)
2. I followed the install instructions (`npm init -f`, ` npm install mathjax-node-page@2.X` and `gem install jekyll-mathjax-csp`.
3. Added the plugin to the `_config.yaml`
4. Added some math to `index.md`:
```markdown
---
layout: default
title: "Happy Jekylling!"
---

## You're ready to go!

$$
\begin{eqnarray}
y &=& x^4 + 4      \nonumber \\
  &=& (x^2+2)^2 -4x^2 \nonumber \\
  &\le&(x^2+2)^2    \nonumber
\end{eqnarray}
$$

Start developing your Jekyll website.
```

3. Math doesn't render for me. I also tried `\[` and `/]` as delimiters.

**Comment by fmeum** [comment]
Could you check whether this is fixed in version 1.3.1? 
When I first introduced support for Jekyll 4.0 in version 1.3.0, I messed up a regex. As a result, only math that fits in a single line would be rendered.

**Comment by c0nn3r** [comment]
Thanks fixing it so quickly! You might also want to support `\[...\]` and `\(...\)` delimiters? Thanks for this plugin, it's the only one that does math rendering "right". 😃

**Comment by fmeum** [comment]
> Thanks for this plugin, it's the only one that does math rendering "right".

Thanks! 

> You might also want to support `\[...\]` and `\(...\)` delimiters?

This plugin runs over the output of whatever markdown parser you set in Jekyll. By default, that would be kramdown, which picks up `$$...$$` and translates it into `\[...\]` and `\(...\)` blocks depending on context.

I just confirmed that with default settings, kramdown removes the backslashes from `\[...\]` and `\(...\)` blocks, which breaks the math (see https://kramdown.gettalong.org/syntax.html#automatic-and-manual-escaping). You can work around that by using `\\[...\\]` and `\\(...\\)` instead, but I personally find kramdown's `$$...$$` to work pretty well.
